version: '3'

services:
  db-postgres-simple-social:
    container_name: db-postgres-simple-social
    image: postgres:alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-ss:/data/postgres
    ports:
      - "5432:5432"

volumes:
  db-ss: