# @name sign-up
POST http://localhost:3333/signup
Content-Type: application/json

{
    "username": "profguanabara",
    "nickname": "Gustavo Guanabara",
    "email": "guanabara@email.com",
    "password": "123456",
    "profilePicture": "https://github.com/professorguanabara.png",
    //"banner": "",
    "description": "Nerd por natureza. Professor por vocação. Estou aqui para compartilhar conteúdos para iniciantes em Tecnologia."
}

###

# @name sign-in
POST http://localhost:3333/signin
Content-Type: application/json

{
    "uniquekey": "vini",
    "password": "123456"
}

###

# @name refresh-token

POST http://localhost:3333/refreshtoken
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByb2ZndWFuYWJhcmEiLCJlbWFpbCI6Imd1YW5hYmFyYUBlbWFpbC5jb20iLCJpYXQiOjE3MDAwOTIyODIsImV4cCI6MTcwMDA5NTg4Mn0.GBcCCEPEMC9rrfO_IH3o7MxL4MS5cKrBL3GmWIIf-fc

###

# @name get-users
GET http://localhost:3333/users?page=1&filter=&posts=true&followed=true
Content-Type: application/json

###

# @name get-user
GET http://localhost:3333/user/locoabreu?posts=true

###

# @name update-user
PUT http://localhost:3333/user/Endrick9
Content-Type: application/json
Authorization: Bearer

{
    "username": "Endrick",
    "nickname": "Endrick 'Little'",
    "email": "endrick@contato.com",
    "password": "123456",
    "profilePicture": "{}",
    "banner": "{}",
    "description": "Sou o Endrick! Camisa 9 do Palmeiras e futuro jogador do Real Madrid"
}

###

# @name delete-user
DELETE http://localhost:3333/user/tite
Authorization: Bearer

###

# @name create-follow
POST http://localhost:3333/follow
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx2c291emEiLCJlbWFpbCI6Imx2c291emFAZW1haWwuY29tIiwiaWF0IjoxNzAwMDExMTcwLCJleHAiOjE3MDAwMTQ3NzB9.E5szpmusExnAJKIRxxcAPadn_zXBQ3UhYQ86oQkRjRg

{
    "followed": "profguanabara"
}

###

# @name delete-follow
DELETE http://localhost:3333/follow
Content-Type: application/json
Authorization: Bearer

{
    "follower": "molferferedo",
    "followed": "wfrfer"
}

###

# @name create-post
POST http://localhost:3333/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpbmlnaGlyYWxkaSIsImVtYWlsIjoidmluaWdoaXJhbGRpQGVtYWlsLmNvbSIsImlhdCI6MTcwMDAxMTk2NywiZXhwIjoxNzAwMDE1NTY3fQ.2un82FUGz5Z56KZjjgI4_m_4Cuga3f6Ig3qhkfUNoxQ

{
    "title": "Eai pessoal, sou o Vini e estou desenvolvendo a Simple Social, um ambiente onde todos podem se conectar de uma forma muito simples! Espero que gostem da plataforma."
}

###

# @name get-posts
GET http://localhost:3333/posts

###

# @name get-posts-by-user
GET http://localhost:3333/posts/vinighiraldi

###

# @name get-post-by-id
GET http://localhost:3333/post/1

###

# @name get-feed
GET http://localhost:3333/feed/profguanabara?onlyfriends=
Content-Type: application/json

###

# @name delete-post
DELETE http://localhost:3333/post/7
Authorization: Bearer

###

# @name create-options
POST http://localhost:3333/options
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByb2ZndWFuYWJhcmEiLCJlbWFpbCI6Imd1YW5hYmFyYUBlbWFpbC5jb20iLCJpYXQiOjE3MDAwODU2ODAsImV4cCI6MTcwMDA4OTI4MH0.oA1eLyv1h1uwaCYxvun1j6Ba09e9HGMzURj4drWbfio

{
    "postId": 5,
    "liked": true,
    "favorited": false
}

###

# @name update-options
PUT http://localhost:3333/options
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByb2ZndWFuYWJhcmEiLCJlbWFpbCI6Imd1YW5hYmFyYUBlbWFpbC5jb20iLCJpYXQiOjE3MDAwODU2ODAsImV4cCI6MTcwMDA4OTI4MH0.oA1eLyv1h1uwaCYxvun1j6Ba09e9HGMzURj4drWbfio

{
    "postId": 5,
    "favorited": false,
    "liked": true
}

###

# @name create-comment
POST http://localhost:3333/comment
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx2c291emEiLCJlbWFpbCI6Imx2c291emFAZW1haWwuY29tIiwiaWF0IjoxNzAwMjMwNDkxLCJleHAiOjE3MDAyMzQwOTF9.bycAHGg3Y8jtv516EJSCv1ZmkUbUgoOmYkMNnY43d5E

{
    "postId": 6,
    "comment": "Tava precisando desse vídeo kkkk"
}

###

# @name delete-comment
DELETE http://localhost:3333/comment/10
Authorization: Bearer