# @name sign-up
POST http://localhost:3333/signup
Content-Type: application/json

{
    "username": "Tite",
    "nickname": "tite",
    "email": "tite@contato.com",
    "password": "123456",
    "profilePicture": "{}",
    "banner": "{}",
    "description": "Sou o Tite! Camisa 9 do Palmeiras e futuro jogador do Real Madrid"
}

###

# @name get-users
GET http://localhost:3333/users?page=1
Content-Type: application/json

{
    "posts": true,
    "followed": true
}

###

# @name get-user
GET http://localhost:3333/user/Endrick9

###

# @name update-user
PUT http://localhost:3333/user/Endrick9
Content-Type: application/json

{
    "username": "Endrick",
    "nickname": "Endrick 'Little'",
    "email": "endrick@contato.com",
    "password": "123456",
    "profilePicture": "{}",
    "banner": "{}",
    "description": "Sou o Endrick! Camisa 9 do Palmeiras e futuro jogador do Real Madrid"
}

###

# @name delete-user
DELETE http://localhost:3333/user/tite

###

# @name create-follow
POST http://localhost:3333/follow
Content-Type: application/json

{
    "follower": "Endrick9",
    "followed": "moledo"
}

###

# @name delete-follow
DELETE http://localhost:3333/follow
Content-Type: application/json

{
    "follower": "molferferedo",
    "followed": "wfrfer"
}

###

# @name create-post
POST http://localhost:3333/post
Content-Type: application/json

{
    "title": "Calma ai calabreso",
    "userId": "moledo"
}

###

# @name get-posts
GET http://localhost:3333/posts

###

# @name get-posts-by-user
GET http://localhost:3333/posts/111

###

# @name delete-post
DELETE http://localhost:3333/post/7

###

# @name create-options
POST http://localhost:3333/options
Content-Type: application/json

{
    "userId": "Vinighiraldi",
    "postId": 1,
    "liked": true,
    "favorited": true
}

###

# @name update-options
PUT http://localhost:3333/options
Content-Type: application/json

{
    "userId": "Moledo",
    "postId": 1,
    "favorited": false,
    "liked": false
}

###

# @name create-comment
POST http://localhost:3333/comment
Content-Type: application/json

{
    "userId": "diegobau",
    "postId": 1,
    "comment": "Boraaaaaaa"
}

###

# @name delete-comment
DELETE http://localhost:3333/comment/10